simpleTCP:
	g++ -o discard discard.cpp -lmymuduo -lpthread -g
	g++ -o daytime daytime.cpp -lmymuduo -lpthread -g
	g++ -o time time.cpp -lmymuduo -lpthread -g
	g++ -o timeclient timeclient.cpp -lmymuduo -lpthread -g
	g++ -o chargen chargen.cpp -lmymuduo -lpthread -g
	g++ -o chargenclient chargenclient.cpp -lmymuduo -lpthread -g

	
clean:
	rm -f discard
	rm -f daytime
	rm -f time
	rm -f timeclient
	rm -f chargen
	rm -f chargenclient
